-- Daily Run: authoritative UTC challenge, three ranked attempts, and public ranking.
-- Run this after supabase-player-identity-auto-submit.sql.

create extension if not exists pgcrypto;

create table if not exists public.daily_run_config (
  singleton boolean primary key default true check (singleton),
  debug_unlimited_attempts boolean not null default false,
  updated_at timestamptz not null default now()
);

insert into public.daily_run_config (singleton, debug_unlimited_attempts)
values (true, false)
on conflict (singleton) do nothing;

alter table public.daily_run_config enable row level security;
revoke all on public.daily_run_config from public, anon, authenticated;

create table if not exists public.daily_challenges (
  id bigint generated by default as identity primary key,
  challenge_date date not null unique,
  seed bigint not null check (seed between 0 and 4294967295),
  theme text not null,
  duration_ms integer not null default 60000 check (duration_ms between 1000 and 300000),
  board_cols smallint not null default 20 check (board_cols >= 3),
  board_rows smallint not null default 32 check (board_rows >= 1),
  ruleset_version text not null default 'snake-rules-v1',
  created_at timestamptz not null default now()
);

create table if not exists public.daily_attempts (
  id uuid primary key default gen_random_uuid(),
  challenge_id bigint not null references public.daily_challenges(id) on delete cascade,
  player_id uuid not null references auth.users(id) on delete cascade,
  attempt_number smallint not null check (attempt_number >= 1),
  request_id uuid not null,
  run_token text not null,
  token_expires_at timestamptz not null,
  status text not null default 'reserved'
    check (status in ('reserved', 'verified', 'rejected')),
  verification_state text not null default 'pending'
    check (verification_state in ('pending', 'verified', 'rejected')),
  score integer check (score is null or score >= 0),
  final_food_ms integer check (final_food_ms is null or final_food_ms >= 0),
  finish_reason text check (finish_reason is null or finish_reason in ('time', 'collision')),
  control_method text check (control_method is null or control_method in ('dpad', 'turn', 'tap', 'keyboard', 'mixed')),
  replay jsonb,
  rejection_reason text,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  unique (challenge_id, player_id, attempt_number),
  unique (challenge_id, player_id, request_id)
);

create index if not exists daily_attempts_player_challenge_idx
  on public.daily_attempts (player_id, challenge_id);

create index if not exists daily_attempts_ranking_idx
  on public.daily_attempts (challenge_id, verification_state, score desc, final_food_ms asc, completed_at asc);

alter table public.daily_challenges enable row level security;
alter table public.daily_attempts enable row level security;

-- Older installs enforced the production limit at the column level. Reservation
-- remains server-controlled, so loosen the constraint to permit explicit debug mode.
alter table public.daily_attempts drop constraint if exists daily_attempts_attempt_number_check;
alter table public.daily_attempts add constraint daily_attempts_attempt_number_check
  check (attempt_number >= 1);

revoke all on public.daily_challenges from public, anon, authenticated;
revoke all on public.daily_attempts from public, anon, authenticated;

create or replace function public.ensure_daily_challenge(
  p_date date default (timezone('utc', now()))::date
)
returns public.daily_challenges
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $$
declare
  v_challenge public.daily_challenges;
  v_seed bigint;
  v_themes text[] := array[
    'default', 'mario', 'zelda', 'streetfighter', 'dk', 'sonic',
    'tetris', 'halo', 'contra', 'lego', 'simpsons', 'got'
  ];
begin
  select * into v_challenge
  from public.daily_challenges
  where challenge_date = p_date;

  if found then
    return v_challenge;
  end if;

  v_seed := ('x' || substr(md5('snake-daily-v1:' || p_date::text), 1, 8))::bit(32)::bigint;

  insert into public.daily_challenges (
    challenge_date, seed, theme, duration_ms, board_cols, board_rows, ruleset_version
  ) values (
    p_date,
    v_seed,
    v_themes[((v_seed % array_length(v_themes, 1)) + 1)::integer],
    60000,
    20,
    32,
    'snake-rules-v1'
  )
  on conflict (challenge_date) do nothing;

  select * into strict v_challenge
  from public.daily_challenges
  where challenge_date = p_date;

  return v_challenge;
end;
$$;

revoke all on function public.ensure_daily_challenge(date) from public, anon, authenticated;

create or replace function public.get_daily_challenge()
returns table (
  challenge_id bigint,
  challenge_date date,
  challenge_number integer,
  seed bigint,
  theme text,
  duration_ms integer,
  board_cols smallint,
  board_rows smallint,
  ruleset_version text,
  attempts_used integer,
  attempts_remaining integer
)
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $$
declare
  v_uid uuid := auth.uid();
  v_challenge public.daily_challenges;
  v_used integer := 0;
  v_debug boolean := false;
begin
  v_challenge := public.ensure_daily_challenge((timezone('utc', now()))::date);

  select c.debug_unlimited_attempts into v_debug
  from public.daily_run_config c
  where c.singleton = true;

  if v_uid is not null then
    select count(*)::integer into v_used
    from public.daily_attempts a
    where a.challenge_id = v_challenge.id
      and a.player_id = v_uid;
  end if;

  return query select
    v_challenge.id,
    v_challenge.challenge_date,
    greatest(1, (v_challenge.challenge_date - date '2026-01-01') + 1),
    v_challenge.seed,
    v_challenge.theme,
    v_challenge.duration_ms,
    v_challenge.board_cols,
    v_challenge.board_rows,
    v_challenge.ruleset_version,
    v_used,
    case when v_debug then -1 else greatest(0, 3 - v_used) end;
end;
$$;

revoke all on function public.get_daily_challenge() from public, anon;
grant execute on function public.get_daily_challenge() to authenticated;

create or replace function public.start_daily_attempt(p_request_id uuid)
returns table (
  ranked boolean,
  attempt_id uuid,
  attempt_number smallint,
  attempts_remaining integer,
  run_token text,
  challenge_id bigint,
  challenge_date date,
  challenge_number integer,
  seed bigint,
  theme text,
  duration_ms integer,
  board_cols smallint,
  board_rows smallint,
  ruleset_version text
)
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $$
declare
  v_uid uuid := auth.uid();
  v_challenge public.daily_challenges;
  v_attempt public.daily_attempts;
  v_used integer;
  v_token text;
  v_debug boolean := false;
begin
  if v_uid is null then
    raise exception 'DAILY_AUTH_REQUIRED';
  end if;

  if p_request_id is null then
    raise exception 'DAILY_REQUEST_ID_REQUIRED';
  end if;

  if not exists (select 1 from public.player_profiles p where p.id = v_uid) then
    raise exception 'DAILY_PROFILE_REQUIRED';
  end if;

  v_challenge := public.ensure_daily_challenge((timezone('utc', now()))::date);

  select c.debug_unlimited_attempts into v_debug
  from public.daily_run_config c
  where c.singleton = true;

  -- Serialize reservations for this player and challenge. The request UUID
  -- makes retries idempotent if the network loses the original response.
  perform pg_advisory_xact_lock(hashtextextended(v_uid::text || ':' || v_challenge.id::text, 0));

  select * into v_attempt
  from public.daily_attempts a
  where a.challenge_id = v_challenge.id
    and a.player_id = v_uid
    and a.request_id = p_request_id;

  if found then
    select count(*)::integer into v_used
    from public.daily_attempts a
    where a.challenge_id = v_challenge.id and a.player_id = v_uid;

    return query select
      true, v_attempt.id, v_attempt.attempt_number,
      case when v_debug then -1 else greatest(0, 3 - v_used) end,
      v_attempt.run_token, v_challenge.id, v_challenge.challenge_date,
      greatest(1, (v_challenge.challenge_date - date '2026-01-01') + 1),
      v_challenge.seed, v_challenge.theme, v_challenge.duration_ms,
      v_challenge.board_cols, v_challenge.board_rows, v_challenge.ruleset_version;
    return;
  end if;

  select count(*)::integer into v_used
  from public.daily_attempts a
  where a.challenge_id = v_challenge.id and a.player_id = v_uid;

  if not v_debug and v_used >= 3 then
    return query select
      false, null::uuid, null::smallint, 0, null::text,
      v_challenge.id, v_challenge.challenge_date,
      greatest(1, (v_challenge.challenge_date - date '2026-01-01') + 1),
      v_challenge.seed, v_challenge.theme, v_challenge.duration_ms,
      v_challenge.board_cols, v_challenge.board_rows, v_challenge.ruleset_version;
    return;
  end if;

  v_token := encode(gen_random_bytes(32), 'hex');

  insert into public.daily_attempts (
    challenge_id, player_id, attempt_number, request_id, run_token, token_expires_at
  ) values (
    v_challenge.id, v_uid, (v_used + 1)::smallint, p_request_id,
    v_token, now() + interval '10 minutes'
  ) returning * into v_attempt;

  return query select
    true, v_attempt.id, v_attempt.attempt_number,
    case when v_debug then -1 else greatest(0, 2 - v_used) end,
    v_token, v_challenge.id, v_challenge.challenge_date,
    greatest(1, (v_challenge.challenge_date - date '2026-01-01') + 1),
    v_challenge.seed, v_challenge.theme, v_challenge.duration_ms,
    v_challenge.board_cols, v_challenge.board_rows, v_challenge.ruleset_version;
end;
$$;

revoke all on function public.start_daily_attempt(uuid) from public, anon;
grant execute on function public.start_daily_attempt(uuid) to authenticated;

create or replace view public.daily_leaderboard as
with best_per_player as (
  select distinct on (a.challenge_id, a.player_id)
    a.challenge_id,
    a.player_id,
    a.attempt_number,
    a.score,
    a.final_food_ms,
    a.control_method,
    a.completed_at
  from public.daily_attempts a
  where a.verification_state = 'verified'
  order by a.challenge_id, a.player_id, a.score desc, a.final_food_ms asc nulls last, a.completed_at asc
), ranked as (
  select
    b.*,
    rank() over (
      partition by b.challenge_id
      order by b.score desc, b.final_food_ms asc nulls last, b.completed_at asc
    )::bigint as leaderboard_rank
  from best_per_player b
)
select
  c.challenge_date,
  greatest(1, (c.challenge_date - date '2026-01-01') + 1) as challenge_number,
  p.initials as name,
  p.player_code,
  r.player_id,
  r.score,
  r.final_food_ms,
  r.control_method,
  c.theme,
  r.attempt_number,
  r.completed_at,
  r.leaderboard_rank
from ranked r
join public.daily_challenges c on c.id = r.challenge_id
join public.player_profiles p on p.id = r.player_id;

revoke all on public.daily_leaderboard from public;
grant select on public.daily_leaderboard to anon, authenticated;

create or replace view public.daily_leaderboard_days as
with day_entries as (
  select
    challenge_date,
    count(*)::bigint as participant_count,
    max(score)::integer as top_score
  from public.daily_leaderboard
  group by challenge_date
), winners as (
  select
    challenge_date,
    name as winner_name,
    player_code as winner_player_code,
    player_id as winner_player_id,
    score as winning_score,
    final_food_ms as winning_final_food_ms,
    control_method as winning_control_method,
    completed_at as winning_completed_at
  from public.daily_leaderboard
  where leaderboard_rank = 1
)
select
  c.challenge_date,
  greatest(1, (c.challenge_date - date '2026-01-01') + 1) as challenge_number,
  c.theme,
  coalesce(e.participant_count, 0)::bigint as participant_count,
  w.winner_name,
  w.winner_player_code,
  w.winner_player_id,
  coalesce(w.winning_score, e.top_score) as winning_score,
  w.winning_final_food_ms,
  w.winning_control_method,
  w.winning_completed_at
from public.daily_challenges c
left join day_entries e on e.challenge_date = c.challenge_date
left join winners w on w.challenge_date = c.challenge_date;

create or replace view public.daily_player_stats as
with entries as (
  select *
  from public.daily_leaderboard
  where challenge_date < (now() at time zone 'utc')::date
), global_dates as (
  select max(challenge_date) as latest_ranked_date from entries
), player_totals as (
  select
    player_id,
    count(*)::bigint as days_played,
    count(*) filter (where leaderboard_rank = 1)::bigint as wins,
    count(*) filter (where leaderboard_rank <= 3)::bigint as podiums,
    count(*) filter (where leaderboard_rank <= 10)::bigint as top_tens,
    min(leaderboard_rank)::bigint as best_finish,
    round(avg(leaderboard_rank)::numeric, 2) as average_finish,
    max(score)::integer as best_score,
    sum(score)::bigint as total_score,
    max(challenge_date) as last_played_date
  from entries
  group by player_id
), participation_numbered as (
  select
    player_id,
    challenge_date,
    challenge_date - (row_number() over (
      partition by player_id order by challenge_date
    ))::integer as streak_group
  from entries
), participation_islands as (
  select
    player_id,
    min(challenge_date) as streak_start,
    max(challenge_date) as streak_end,
    count(*)::bigint as streak_length
  from participation_numbered
  group by player_id, streak_group
), participation_stats as (
  select
    i.player_id,
    max(i.streak_length)::bigint as longest_play_streak,
    coalesce(max(i.streak_length) filter (
      where i.streak_end = g.latest_ranked_date
    ), 0)::bigint as current_play_streak
  from participation_islands i
  cross join global_dates g
  group by i.player_id
), win_numbered as (
  select
    player_id,
    challenge_date,
    challenge_date - (row_number() over (
      partition by player_id order by challenge_date
    ))::integer as streak_group
  from entries
  where leaderboard_rank = 1
), win_islands as (
  select
    player_id,
    min(challenge_date) as streak_start,
    max(challenge_date) as streak_end,
    count(*)::bigint as streak_length
  from win_numbered
  group by player_id, streak_group
), win_stats as (
  select
    i.player_id,
    max(i.streak_length)::bigint as longest_win_streak,
    coalesce(max(i.streak_length) filter (
      where i.streak_end = g.latest_ranked_date
    ), 0)::bigint as current_win_streak
  from win_islands i
  cross join global_dates g
  group by i.player_id
)
select
  p.id as player_id,
  p.initials as name,
  p.player_code,
  t.days_played,
  t.wins,
  t.podiums,
  t.top_tens,
  t.best_finish,
  t.average_finish,
  t.best_score,
  t.total_score,
  round((100 * t.wins::numeric / nullif(t.days_played, 0)), 1) as win_rate_pct,
  coalesce(ps.current_play_streak, 0)::bigint as current_play_streak,
  coalesce(ps.longest_play_streak, 0)::bigint as longest_play_streak,
  coalesce(ws.current_win_streak, 0)::bigint as current_win_streak,
  coalesce(ws.longest_win_streak, 0)::bigint as longest_win_streak,
  t.last_played_date
from player_totals t
join public.player_profiles p on p.id = t.player_id
left join participation_stats ps on ps.player_id = t.player_id
left join win_stats ws on ws.player_id = t.player_id;

revoke all on public.daily_leaderboard_days from public;
revoke all on public.daily_player_stats from public;
grant select on public.daily_leaderboard_days to anon, authenticated;
grant select on public.daily_player_stats to anon, authenticated;

comment on table public.daily_attempts is
  'Server-reserved Daily Run attempts. Initial launch permits anonymous device-bound Auth users with player profiles.';

comment on function public.start_daily_attempt(uuid) is
  'Atomically reserves one of three UTC-day ranked attempts; request UUID retries are idempotent.';
